Sending first message (attempt 1/3)...
Error sending: HTTPConnectionPool(host='qa.internal.uat.cstar.pagopa.it', port=80): Max retries exceeded with url: /send/gpd/message (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f818d3e8d70>: Failed to resolve 'qa.internal.uat.cstar.pagopa.it' ([Errno -2] Name or service not known)")). Retrying in 5 seconds...
Sending first message (attempt 2/3)...
Error sending: HTTPConnectionPool(host='qa.internal.uat.cstar.pagopa.it', port=80): Max retries exceeded with url: /send/gpd/message (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f818d352710>: Failed to resolve 'qa.internal.uat.cstar.pagopa.it' ([Errno -2] Name or service not known)")). Retrying in 5 seconds...
Sending first message (attempt 3/3)...
